### ISSUE TITLE
Shitty logger

### ISSUE THREAD

**Issue by Noticing** [LocalsGitHub/Discord-Info-Logger#11]
This logger is skidded + You need to tell the victim to install python and the modules LMFAOOOO

**Comment by LocalsGitHub** [comment]
If you had eyes and a brain you would have seen that I gave credits where credits are due.

Your ego is so huge that you don't even do the research on the things you say.
The "victim" does not need python or the modules because of something called pyinstaller. It seems your peanut brain cannot process that though.

**Comment by Noticing** [comment]
why did you upload it? all of the code isnt even yours this is a useless repo LOOOOOOOOOOOOOOOOOOOL

**Comment by LocalsGitHub** [comment]
1. upload what?
2. some isnt some is. that's why there's a section called "credits" 
3. you must be laughing at yourself because there's nothing funny here LMAOOOOOO

**Comment by Noticing** [comment]
1. Why did upload the logger (use context)
2. You think you know it all
3. Im laughing at how retarded you are

**Comment by LocalsGitHub** [comment]
1. i uploaded the logger because people were asking me for one for some reason, and there are very shit loggers out with the same pasted, logger (checksums). the only viable logger is mericuial but that's in c# so its not practical.
2. I've told you this before, but i forgot that you have the memory of a fish. 
3. that's ironic considering what your saying

**Comment by LocalsGitHub** [comment]
nice edit while i was typing

1. already explained this
2. I'm following a design pattern that I've seen in multiple repos, and people are usually scrolling all the way down to make sure they don't miss anything, etc
3. not retarded

**Comment by LocalsGitHub** [comment]
btw im aware that some of the code (the token logger) isn't optimized/ can be written better. i didn't want to touch checksums logger, but if i really wanted to i can fix some of the issues that you mentioned in your discord serer.
